import type { Metadata } from "next";
import { siteConfig } from "./site";

/**
 * Share image generated by src/app/opengraph-image.tsx. Next.js only applies it
 * automatically to pages that don't set their own `openGraph`, so pageMetadata
 * references it explicitly.
 */
const shareImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${siteConfig.name} — ${siteConfig.tagline}`,
};

/**
 * Builds a page's metadata with its own canonical URL and share (Open Graph /
 * X) tags. Without this, pages inherit the root layout's share tags, so sharing
 * e.g. /about would link to and describe the home page.
 */
export function pageMetadata({
  title,
  description,
  path,
}: {
  title: string;
  description: string;
  path: string;
}): Metadata {
  const fullTitle = `${title} | ${siteConfig.name}`;
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: "en_US",
      siteName: siteConfig.name,
      url: path,
      title: fullTitle,
      description,
      images: [shareImage],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [shareImage],
    },
  };
}
